on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest # or macos-latest, ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Noeode
        uses: actions/setup-node@v2
        with:
          node-version: latest

      - uses: microsoft/playwright-github-action@v1

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
